# Generated by Django 4.1 on 2023-06-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
