# Generated by Django 4.1 on 2023-06-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
