# Generated by Django 4.1 on 2023-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
