# Generated by Django 4.1 on 2023-06-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='Категория'),
        ),
    ]
